
// Insult lists
let insultStarter = [
,"you" 
,"your beloved auntie" 
,"your country"
,"your cousin's car"
,"your face"
,"your father"
,"your favourite Bond actor"
,"your hat"
,"your house"
,"your hovercraft"
,"your husband"
,"your Kettle"
,"your liver"
,"your math teacher"
,"your mother"
,"your pimply arse"
,"your sense of style"
,"your sister"
,"your sins"
,"your son"
,"your wife"
] 
let insultSoftEnding = [
    ," [is/are] afraid of my minigun"
    ," [is/are] an ill-nurtured whey face"
    ," [is/are] an old bugger" 
    ," [is/are] an organ in your abdomen"
    ," [is/are] deceased"
    ," [is/are] dull and ugly"
    ," [is/are] feeling a little psychotic this morning"
    ," [is/are] full of eels"
    ," [is/are] getting fat"
    ," [is/are] gonna burst with piss"
    ," [is/are] interested in photography"
    ," [is/are] minging"
    ," [is/are] no more"
    ," [is/are] not a part of Europe"
    ," [is/are] not interesting"
    ," [is/are] not migratory"
    ," [is/are] not my creation"
    ," [is/are] not Serious"
    ," [is/are] old"
    ," [is/are] racist"
    ," [is/are] rather plain"
    ," [is/are] rude"
    ," [is/are] scratched"
    ," [is/are] silly"
    ," [is/are] sinful [Postal Dude]"
    ," [is/are] stone dead"
    ," [is/are] very naughty"
    ," [is/are] vile"
    ," [is/are] where you can sit only in train compartment"
    ," [is/are] worthless"
    ," [was/were] born in"
    ," [was/were] burnt like a witch"
    ," [was/were] defeated by"
    ," [was/were] in jail"
    ," [was/were] owned by"
    ," [was/were] teabagged by"
    ," [has/have] a steaming romp with"
    ," [has/have] an unsightly face"
    ," [has/have] bad breath"
    ," [has/have] bum cancer"
    ," [has/have] no life experience"
    ," [has/have] not finished puberty"
    ," [has/have] not so much brain as ear wax"
    ," [has/have] only local multiplayer"
    ," [has/have] tiny feet"
    ," [has/have] worse hair than"
    ," act(s) like"
    ," admire(s) pictures of"
    ," ate Yul Brynner with"
    ," belong(s) in a cage"
    ," bother(s) me"
    ," bring(s) insults to a sword fight"
    ," can be found in Pokémon GO"
    ," can lick my lead"
    ," can not buy a Stairway to Heaven"
    ," can't dance"
    ," can't exercise because of"
    ," can't hold liquor"
    ," can't tie a tie"
    ," change(s) into"
    ," dance(s) like"
    ," died because of"
    ," do(es)n't like"
    ," do(es)n't own a colour telly"
    ," donated organs for"
    ," drunk with"
    ," eat(s) only non-gluten lembas"
    ," enjoyed Batman v Superman"
    ," fart(s) in your general direction"
    ," farted on"
    ," found a new application for a cat's butt"
    ," give(s) a butcher's hook at"
    ," go(es) around murdering people"
    ," had too much of Fungi from Yuggoth"
    ," hide(s) in this shrubbery"
    ," like(s) running with scissors"
    ," like(s) to flash in the park"
    ," look(s) like"
    ," look(s) like a sad lemur"
    ," made a poor deal with"
    ," make(s) fun of the Pope"
    ," make(s) me sick"
    ," move(s) like a pregnant yak"
    ," must be fun at parties"
    ," need(s) a liver transplant [Serious Sam]"
    ," never heard the Call of Cthulhu"
    ," never partied in Moscow"
    ," never watched Star Wars"
    ," pissed on"
    ," play(s) hidden object games"
    ," pre-ordered No Man's Sky"
    ," probably murdered"
    ," poses nude for"
    ," put(s) on granny's clothing"
    ," read(s) Necronomicon with"
    ," secretly adore(s)"
    ," send(s) you warmest pots and dishes"
    ," signed my petition"
    ," sit(s) next to"
    ," smell(s) of"
    ," stalked"
    ," still use(s) Windows Vista"
    ," suck(s) at Overwatch"
    ," support(s)"
    ," swallowed a chewing gum"
    ," talk(s) to strangers"
    ," taste(s) like"
    ," tell(s) dirty jokes at funerals"
    ," used to steal from orphans"
    ," vomit(s) after drinking vodka"
    ," walk(s) silly"
    ," want(s) some Wang *Lo Wang"
    ," wanted to be"
    ," wear(s) second-hand clothes"
    ," went to the Mountain of Madness with"
    ," will always be alone"
    ," will be chopped to bits"
    ," will be damned for eternity"
    ," will disembowel"
    ," will murder for a seat reservation"
    ," will reincarnate as a pigeon only in afterlife"
    ," will soon kick the bucket"
    ," worked with"
]

// random insult picker
let randomInsultStarter = Math.floor(Math.random()*insultStarter.length);

let randomInsultMiddle = Math.floor(Math.random()*insultSoftEnding.length);

// insult level declarations
let level1Insult = insultStarter[randomInsultStarter] + (insultSoftEnding[randomInsultMiddle] + ".");

console.log(level1Insult);


